### ISSUE TITLE
Refactor `DOOR43_CATALOG`

### ISSUE THREAD

**Issue by theNerd247** [unfoldingWord/translation-helps-rcl#113]
The following functions need `DOOR43_CATALOG` constant to be abstracted.

## Process:

see https://github.com/unfoldingWord/translation-helps-rcl/issues/114

```haskell

newVarName = "door43Catalog"

main = do
  sequence refactorDoor43Catalog ["loadGlBible", "getGlAlignmentBiblesList"]
  removeConstant DOOR43_CATALOG
  sequence abstract allRepositoriesUsingTranslationHelps

refactorDoor43Catalog =
  def
  >> replaceName "DOOR43_CATALOG" newVarName
  >> abstract

abstract = id >|< abstractLocalFunc

abstractLocalFunc = 
  prependVarNameToFuncDef newVarName
  >> callsites 
  >> sequence (applyVar newVarName >> abstract)
```

**Comment by PhotoNomad0** [comment]
@theNerd247 Maybe I am misunderstanding what you are intending here.  My thoughts are that rather than abstracting DOOR43_CATALOG, that that it should probably be removed from this library.  Instead the library should be using the `owner` passed in by the app.  Some of the back story: On git.door43.org, originally we only had one official catalog (Door43_Catalog) for released bible resources used in our apps.  And we had an official release process where interdependent repos were verified to be in sync before each release.  That was OK when we only regularly releasing one Gateway Language (GL), but it didn't scale well as we were partnering with other groups working on different GLs.  So then we pivoted to allowing each GL to manage their own releases, so now the apps can use content from any owner (or org) on git.door43.org.  And they select the owner/org in the app when they start working, and that gets passed down to the translation-helps-rcl to fetch the repo from the appropriate owner/org specified in the variable `owner`.  Let's meet early next week so I can show you some of the bigger picture.

@kintsoogi

**Comment by theNerd247** [comment]
Closing because I discovered I can transfer the issue from gateway-edit to translation-helps-rcl..

See #114 now

**Comment by PhotoNomad0** [comment]
> Closing because I discovered I can transfer the issue from gateway-edit to translation-helps-rcl..
> 
> See #114 now

@theNerd247 Check with @birchamp before moving the issue.  Normally if the issue is created on the app, we leave it there.  Also if there is an issue that was created in an rcl, we would then create issues for each app that needs to be updated to use the new fix.
